# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [feature/update]
  pull_request:
    branches: [feature/update]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Build APP
        run: yarn generate:github-page

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/
          force_orphan: true
